using System;
using System.Collections.Generic;
using System.Text;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Checkmarx.Model;
//
//    var scanSettings = ScanSettings.FromJson(jsonString);

namespace Checkmarx.API
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ScanSettings
    {
        [JsonProperty("project")]
        public EngineConfiguration Project { get; set; }

        [JsonProperty("preset")]
        public EngineConfiguration Preset { get; set; }

        [JsonProperty("engineConfiguration")]
        public EngineConfiguration EngineConfiguration { get; set; }

        [JsonProperty("postScanAction")]
        public object PostScanAction { get; set; }

        [JsonProperty("emailNotifications")]
        public EmailNotifications EmailNotifications { get; set; }
    }

    public partial class ScanDetails
    {
        [JsonProperty("projectId")]
        public long ProjectId { get; set; }

        [JsonProperty("isIncremental")]
        public bool IsIncremental { get; set; }

        [JsonProperty("isPublic")]
        public bool IsPublic { get; set; }

        [JsonProperty("forceScan")]
        public bool ForceScan { get; set; }

        [JsonProperty("comment")]
        public string Comment { get; set; }
    }

    public partial class EmailNotifications
    {
        [JsonProperty("failedScan")]
        public List<object> FailedScan { get; set; }

        [JsonProperty("beforeScan")]
        public List<object> BeforeScan { get; set; }

        [JsonProperty("afterScan")]
        public List<object> AfterScan { get; set; }
    }

    public partial class EngineConfiguration
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("link")]
        public Link Link { get; set; }
    }

    public partial class GitSettings
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("branch")]
        public string Branch { get; set; }

        [JsonProperty("useSsh")]
        public bool UseSsh { get; set; }

        [JsonProperty("link")]
        public Link Link { get; set; }
    }

    public partial class Link
    {
        [JsonProperty("rel")]
        public string Rel { get; set; }

        [JsonProperty("uri")]
        public string Uri { get; set; }
    }

   
}

