//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cxPriorityWebService
{
    using Checkmarx.API;
    using System;
    using System.Linq;
    using System.ServiceModel;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CxWSBasicRepsonse", Namespace="http://Checkmarx.com")]
    public partial class CxWSBasicResponse : object
    {
        
        private bool IsSuccesfullField;
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSuccesfull
        {
            get
            {
                return this.IsSuccesfullField;
            }
            set
            {
                this.IsSuccesfullField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CxWSResponceScanResultsPriority", Namespace="http://Checkmarx.com")]
    public partial class CxWSResponseScanResultsPriority : cxPriorityWebService.CxWSBasicResponse
    {
        
        private cxPriorityWebService.CxWSSingleResultDataPriority[] ResultsField;
        
        private bool SastRemediationEnabledField;
        
        private bool CxMnoInstalledField;
        
        private int? TotalResultsCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public cxPriorityWebService.CxWSSingleResultDataPriority[] Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SastRemediationEnabled
        {
            get
            {
                return this.SastRemediationEnabledField;
            }
            set
            {
                this.SastRemediationEnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool CxMnoInstalled
        {
            get
            {
                return this.CxMnoInstalledField;
            }
            set
            {
                this.CxMnoInstalledField = value;
            }
        }

        // It should stay as IsRequired=false -> Bellow version 9.4 the response does not contain total results count
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=false, Order=3)]
        public int? TotalResultsCount
        {
            get
            {
                return this.TotalResultsCountField;
            }
            set
            {
                this.TotalResultsCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CxWSSingleResultDataPriority", Namespace="http://Checkmarx.com")]
    public partial class CxWSSingleResultDataPriority
    {

        private long QueryIdField;

        private long PathIdField;

        private string SourceFolderField;

        private string SourceFileField;

        private long SourceLineField;

        private string SourceObjectField;

        private string DestFolderField;

        private string DestFileField;

        private long DestLineField;

        private long SimilarityIDField;

        private int NumberOfNodesField;

        private string DestObjectField;

        private string CommentField;

        private int StateField;

        private int SeverityField;

        private string AssignedUserField;

        private System.Nullable<int> ConfidenceLevelField;

        private CompareStatusType ResultStatusField;

        private string IssueTicketIDField;

        private long QueryVersionCodeField;

        private System.Nullable<double> CxRankField;

        private string BflNodeShortNameField;

        private System.Nullable<int> BflGroupSizeField;

        private System.Nullable<System.DateTime> DateField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public long QueryId
        {
            get
            {
                return this.QueryIdField;
            }
            set
            {
                this.QueryIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public long PathId
        {
            get
            {
                return this.PathIdField;
            }
            set
            {
                this.PathIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string SourceFolder
        {
            get
            {
                return this.SourceFolderField;
            }
            set
            {
                this.SourceFolderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string SourceFile
        {
            get
            {
                return this.SourceFileField;
            }
            set
            {
                this.SourceFileField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public long SourceLine
        {
            get
            {
                return this.SourceLineField;
            }
            set
            {
                this.SourceLineField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string SourceObject
        {
            get
            {
                return this.SourceObjectField;
            }
            set
            {
                this.SourceObjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string DestFolder
        {
            get
            {
                return this.DestFolderField;
            }
            set
            {
                this.DestFolderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string DestFile
        {
            get
            {
                return this.DestFileField;
            }
            set
            {
                this.DestFileField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 8)]
        public long DestLine
        {
            get
            {
                return this.DestLineField;
            }
            set
            {
                this.DestLineField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, Order = 9)]
        public long SimilarityID
        {
            get
            {
                return this.SimilarityIDField;
            }
            set
            {
                this.SimilarityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 10)]
        public int NumberOfNodes
        {
            get
            {
                return this.NumberOfNodesField;
            }
            set
            {
                this.NumberOfNodesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 11)]
        public string DestObject
        {
            get
            {
                return this.DestObjectField;
            }
            set
            {
                this.DestObjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 12)]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 13)]
        public int State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 14)]
        public int Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 15)]
        public string AssignedUser
        {
            get
            {
                return this.AssignedUserField;
            }
            set
            {
                this.AssignedUserField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 16)]
        public System.Nullable<int> ConfidenceLevel
        {
            get
            {
                return this.ConfidenceLevelField;
            }
            set
            {
                this.ConfidenceLevelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 17)]
        public CompareStatusType ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 18)]
        public string IssueTicketID
        {
            get
            {
                return this.IssueTicketIDField;
            }
            set
            {
                this.IssueTicketIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 19)]
        public long QueryVersionCode
        {
            get
            {
                return this.QueryVersionCodeField;
            }
            set
            {
                this.QueryVersionCodeField = value;
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 20)]
        public System.Nullable<double> CxRank
        {
            get
            {
                return this.CxRankField;
            }
            set
            {
                this.CxRankField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 21)]
        public string BflNodeShortName
        {
            get
            {
                return this.BflNodeShortNameField;
            }
            set
            {
                this.BflNodeShortNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 22)]
        public System.Nullable<int> BflGroupSize
        {
            get
            {
                return this.BflGroupSizeField;
            }
            set
            {
                this.BflGroupSizeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 23)]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompareStatusType", Namespace="CxDataTypes.xsd")]
    public enum CompareStatusType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fixed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reoccured = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Checkmarx.com", ConfigurationName="cxPriorityWebService.CxPriorityServiceSoap")]
    public interface CxPriorityServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://Checkmarx.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForQuery", ReplyAction="*")]
        cxPriorityWebService.GetResultsForQueryResponse GetResultsForQuery(cxPriorityWebService.GetResultsForQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryResponse> GetResultsForQueryAsync(cxPriorityWebService.GetResultsForQueryRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://Checkmarx.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForQueryQroup", ReplyAction="*")]
        cxPriorityWebService.GetResultsForQueryQroupResponse GetResultsForQueryQroup(cxPriorityWebService.GetResultsForQueryQroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForQueryQroup", ReplyAction="*")]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryQroupResponse> GetResultsForQueryQroupAsync(cxPriorityWebService.GetResultsForQueryQroupRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://Checkmarx.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForScanByLanguage", ReplyAction="*")]
        cxPriorityWebService.GetResultsForScanByLanguageResponse GetResultsForScanByLanguage(cxPriorityWebService.GetResultsForScanByLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForScanByLanguage", ReplyAction="*")]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanByLanguageResponse> GetResultsForScanByLanguageAsync(cxPriorityWebService.GetResultsForScanByLanguageRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://Checkmarx.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForScan", ReplyAction="*")]
        cxPriorityWebService.GetResultsForScanResponse GetResultsForScan(cxPriorityWebService.GetResultsForScanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForScan", ReplyAction="*")]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanResponse> GetResultsForScanAsync(cxPriorityWebService.GetResultsForScanRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://Checkmarx.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsBySeverity", ReplyAction="*")]
        cxPriorityWebService.GetResultsBySeverityResponse GetResultsBySeverity(cxPriorityWebService.GetResultsBySeverityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsBySeverity", ReplyAction="*")]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsBySeverityResponse> GetResultsBySeverityAsync(cxPriorityWebService.GetResultsBySeverityRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://Checkmarx.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForQueryWithPaging", ReplyAction="*")]
        cxPriorityWebService.GetResultsForQueryWithPagingResponse GetResultsForQueryWithPaging(cxPriorityWebService.GetResultsForQueryWithPagingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForQueryWithPaging", ReplyAction="*")]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryWithPagingResponse> GetResultsForQueryWithPagingAsync(cxPriorityWebService.GetResultsForQueryWithPagingRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://Checkmarx.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForScanByLanguageWithPaging", ReplyAction="*")]
        cxPriorityWebService.GetResultsForScanByLanguageWithPagingResponse GetResultsForScanByLanguageWithPaging(cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForScanByLanguageWithPaging", ReplyAction="*")]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanByLanguageWithPagingResponse> GetResultsForScanByLanguageWithPagingAsync(cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://Checkmarx.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForScanWithPaging", ReplyAction="*")]
        cxPriorityWebService.GetResultsForScanWithPagingResponse GetResultsForScanWithPaging(cxPriorityWebService.GetResultsForScanWithPagingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForScanWithPaging", ReplyAction="*")]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanWithPagingResponse> GetResultsForScanWithPagingAsync(cxPriorityWebService.GetResultsForScanWithPagingRequest request);
        
        // CODEGEN: Generating message contract since element name sessionId from namespace http://Checkmarx.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsBySeverityWithPaging", ReplyAction="*")]
        cxPriorityWebService.GetResultsBySeverityWithPagingResponse GetResultsBySeverityWithPaging(cxPriorityWebService.GetResultsBySeverityWithPagingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsBySeverityWithPaging", ReplyAction="*")]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsBySeverityWithPagingResponse> GetResultsBySeverityWithPagingAsync(cxPriorityWebService.GetResultsBySeverityWithPagingRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://Checkmarx.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForQueryQroupWithPaging", ReplyAction="*")]
        cxPriorityWebService.GetResultsForQueryQroupWithPagingResponse GetResultsForQueryQroupWithPaging(cxPriorityWebService.GetResultsForQueryQroupWithPagingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Checkmarx.com/GetResultsForQueryQroupWithPaging", ReplyAction="*")]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryQroupWithPagingResponse> GetResultsForQueryQroupWithPagingAsync(cxPriorityWebService.GetResultsForQueryQroupWithPagingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForQuery", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForQueryRequestBody Body;
        
        public GetResultsForQueryRequest()
        {
        }
        
        public GetResultsForQueryRequest(cxPriorityWebService.GetResultsForQueryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForQueryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long scanId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long queryId;
        
        public GetResultsForQueryRequestBody()
        {
        }
        
        public GetResultsForQueryRequestBody(string sessionID, long scanId, long queryId)
        {
            this.sessionID = sessionID;
            this.scanId = scanId;
            this.queryId = queryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForQueryResponse", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForQueryResponseBody Body;
        
        public GetResultsForQueryResponse()
        {
        }
        
        public GetResultsForQueryResponse(cxPriorityWebService.GetResultsForQueryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForQueryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryResult;
        
        public GetResultsForQueryResponseBody()
        {
        }
        
        public GetResultsForQueryResponseBody(cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryResult)
        {
            this.GetResultsForQueryResult = GetResultsForQueryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForQueryQroupRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForQueryQroup", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForQueryQroupRequestBody Body;
        
        public GetResultsForQueryQroupRequest()
        {
        }
        
        public GetResultsForQueryQroupRequest(cxPriorityWebService.GetResultsForQueryQroupRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForQueryQroupRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long scanId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long queryGroupId;
        
        public GetResultsForQueryQroupRequestBody()
        {
        }
        
        public GetResultsForQueryQroupRequestBody(string sessionID, long scanId, long queryGroupId)
        {
            this.sessionID = sessionID;
            this.scanId = scanId;
            this.queryGroupId = queryGroupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForQueryQroupResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForQueryQroupResponse", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForQueryQroupResponseBody Body;
        
        public GetResultsForQueryQroupResponse()
        {
        }
        
        public GetResultsForQueryQroupResponse(cxPriorityWebService.GetResultsForQueryQroupResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForQueryQroupResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryQroupResult;
        
        public GetResultsForQueryQroupResponseBody()
        {
        }
        
        public GetResultsForQueryQroupResponseBody(cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryQroupResult)
        {
            this.GetResultsForQueryQroupResult = GetResultsForQueryQroupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForScanByLanguageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForScanByLanguage", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForScanByLanguageRequestBody Body;
        
        public GetResultsForScanByLanguageRequest()
        {
        }
        
        public GetResultsForScanByLanguageRequest(cxPriorityWebService.GetResultsForScanByLanguageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForScanByLanguageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long scanId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Language;
        
        public GetResultsForScanByLanguageRequestBody()
        {
        }
        
        public GetResultsForScanByLanguageRequestBody(string sessionID, long scanId, string Language)
        {
            this.sessionID = sessionID;
            this.scanId = scanId;
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForScanByLanguageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForScanByLanguageResponse", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForScanByLanguageResponseBody Body;
        
        public GetResultsForScanByLanguageResponse()
        {
        }
        
        public GetResultsForScanByLanguageResponse(cxPriorityWebService.GetResultsForScanByLanguageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForScanByLanguageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanByLanguageResult;
        
        public GetResultsForScanByLanguageResponseBody()
        {
        }
        
        public GetResultsForScanByLanguageResponseBody(cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanByLanguageResult)
        {
            this.GetResultsForScanByLanguageResult = GetResultsForScanByLanguageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForScanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForScan", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForScanRequestBody Body;
        
        public GetResultsForScanRequest()
        {
        }
        
        public GetResultsForScanRequest(cxPriorityWebService.GetResultsForScanRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForScanRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long scanId;
        
        public GetResultsForScanRequestBody()
        {
        }
        
        public GetResultsForScanRequestBody(string sessionID, long scanId)
        {
            this.sessionID = sessionID;
            this.scanId = scanId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForScanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForScanResponse", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForScanResponseBody Body;
        
        public GetResultsForScanResponse()
        {
        }
        
        public GetResultsForScanResponse(cxPriorityWebService.GetResultsForScanResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForScanResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanResult;
        
        public GetResultsForScanResponseBody()
        {
        }
        
        public GetResultsForScanResponseBody(cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanResult)
        {
            this.GetResultsForScanResult = GetResultsForScanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsBySeverityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsBySeverity", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsBySeverityRequestBody Body;
        
        public GetResultsBySeverityRequest()
        {
        }
        
        public GetResultsBySeverityRequest(cxPriorityWebService.GetResultsBySeverityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsBySeverityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long scanId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Severity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Language;
        
        public GetResultsBySeverityRequestBody()
        {
        }
        
        public GetResultsBySeverityRequestBody(string sessionId, long scanId, int Severity, string Language)
        {
            this.sessionId = sessionId;
            this.scanId = scanId;
            this.Severity = Severity;
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsBySeverityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsBySeverityResponse", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsBySeverityResponseBody Body;
        
        public GetResultsBySeverityResponse()
        {
        }
        
        public GetResultsBySeverityResponse(cxPriorityWebService.GetResultsBySeverityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsBySeverityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsBySeverityResult;
        
        public GetResultsBySeverityResponseBody()
        {
        }
        
        public GetResultsBySeverityResponseBody(cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsBySeverityResult)
        {
            this.GetResultsBySeverityResult = GetResultsBySeverityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForQueryWithPagingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForQueryWithPaging", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForQueryWithPagingRequestBody Body;
        
        public GetResultsForQueryWithPagingRequest()
        {
        }
        
        public GetResultsForQueryWithPagingRequest(cxPriorityWebService.GetResultsForQueryWithPagingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForQueryWithPagingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long scanId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int skip;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int take;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool calculateTotalResultsCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long queryId;
        
        public GetResultsForQueryWithPagingRequestBody()
        {
        }
        
        public GetResultsForQueryWithPagingRequestBody(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount, long queryId)
        {
            this.sessionID = sessionID;
            this.scanId = scanId;
            this.skip = skip;
            this.take = take;
            this.calculateTotalResultsCount = calculateTotalResultsCount;
            this.queryId = queryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForQueryWithPagingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForQueryWithPagingResponse", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForQueryWithPagingResponseBody Body;
        
        public GetResultsForQueryWithPagingResponse()
        {
        }
        
        public GetResultsForQueryWithPagingResponse(cxPriorityWebService.GetResultsForQueryWithPagingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForQueryWithPagingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryWithPagingResult;
        
        public GetResultsForQueryWithPagingResponseBody()
        {
        }
        
        public GetResultsForQueryWithPagingResponseBody(cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryWithPagingResult)
        {
            this.GetResultsForQueryWithPagingResult = GetResultsForQueryWithPagingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForScanByLanguageWithPagingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForScanByLanguageWithPaging", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequestBody Body;
        
        public GetResultsForScanByLanguageWithPagingRequest()
        {
        }
        
        public GetResultsForScanByLanguageWithPagingRequest(cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForScanByLanguageWithPagingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long scanId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int skip;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int take;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool calculateTotalResultsCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Language;
        
        public GetResultsForScanByLanguageWithPagingRequestBody()
        {
        }
        
        public GetResultsForScanByLanguageWithPagingRequestBody(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount, string Language)
        {
            this.sessionID = sessionID;
            this.scanId = scanId;
            this.skip = skip;
            this.take = take;
            this.calculateTotalResultsCount = calculateTotalResultsCount;
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForScanByLanguageWithPagingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForScanByLanguageWithPagingResponse", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForScanByLanguageWithPagingResponseBody Body;
        
        public GetResultsForScanByLanguageWithPagingResponse()
        {
        }
        
        public GetResultsForScanByLanguageWithPagingResponse(cxPriorityWebService.GetResultsForScanByLanguageWithPagingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForScanByLanguageWithPagingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanByLanguageWithPagingResult;
        
        public GetResultsForScanByLanguageWithPagingResponseBody()
        {
        }
        
        public GetResultsForScanByLanguageWithPagingResponseBody(cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanByLanguageWithPagingResult)
        {
            this.GetResultsForScanByLanguageWithPagingResult = GetResultsForScanByLanguageWithPagingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForScanWithPagingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForScanWithPaging", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForScanWithPagingRequestBody Body;
        
        public GetResultsForScanWithPagingRequest()
        {
        }
        
        public GetResultsForScanWithPagingRequest(cxPriorityWebService.GetResultsForScanWithPagingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForScanWithPagingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long scanId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int skip;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int take;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool calculateTotalResultsCount;
        
        public GetResultsForScanWithPagingRequestBody()
        {
        }
        
        public GetResultsForScanWithPagingRequestBody(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount)
        {
            this.sessionID = sessionID;
            this.scanId = scanId;
            this.skip = skip;
            this.take = take;
            this.calculateTotalResultsCount = calculateTotalResultsCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForScanWithPagingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForScanWithPagingResponse", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForScanWithPagingResponseBody Body;
        
        public GetResultsForScanWithPagingResponse()
        {
        }
        
        public GetResultsForScanWithPagingResponse(cxPriorityWebService.GetResultsForScanWithPagingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForScanWithPagingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanWithPagingResult;
        
        public GetResultsForScanWithPagingResponseBody()
        {
        }
        
        public GetResultsForScanWithPagingResponseBody(cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanWithPagingResult)
        {
            this.GetResultsForScanWithPagingResult = GetResultsForScanWithPagingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsBySeverityWithPagingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsBySeverityWithPaging", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsBySeverityWithPagingRequestBody Body;
        
        public GetResultsBySeverityWithPagingRequest()
        {
        }
        
        public GetResultsBySeverityWithPagingRequest(cxPriorityWebService.GetResultsBySeverityWithPagingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsBySeverityWithPagingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long scanId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int skip;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int take;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool calculateTotalResultsCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Severity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Language;
        
        public GetResultsBySeverityWithPagingRequestBody()
        {
        }
        
        public GetResultsBySeverityWithPagingRequestBody(string sessionId, long scanId, int skip, int take, bool calculateTotalResultsCount, int Severity, string Language)
        {
            this.sessionId = sessionId;
            this.scanId = scanId;
            this.skip = skip;
            this.take = take;
            this.calculateTotalResultsCount = calculateTotalResultsCount;
            this.Severity = Severity;
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsBySeverityWithPagingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsBySeverityWithPagingResponse", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsBySeverityWithPagingResponseBody Body;
        
        public GetResultsBySeverityWithPagingResponse()
        {
        }
        
        public GetResultsBySeverityWithPagingResponse(cxPriorityWebService.GetResultsBySeverityWithPagingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsBySeverityWithPagingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsBySeverityWithPagingResult;
        
        public GetResultsBySeverityWithPagingResponseBody()
        {
        }
        
        public GetResultsBySeverityWithPagingResponseBody(cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsBySeverityWithPagingResult)
        {
            this.GetResultsBySeverityWithPagingResult = GetResultsBySeverityWithPagingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForQueryQroupWithPagingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForQueryQroupWithPaging", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForQueryQroupWithPagingRequestBody Body;
        
        public GetResultsForQueryQroupWithPagingRequest()
        {
        }
        
        public GetResultsForQueryQroupWithPagingRequest(cxPriorityWebService.GetResultsForQueryQroupWithPagingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForQueryQroupWithPagingRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long scanId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int skip;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int take;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool calculateTotalResultsCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long queryGroupId;
        
        public GetResultsForQueryQroupWithPagingRequestBody()
        {
        }
        
        public GetResultsForQueryQroupWithPagingRequestBody(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount, long queryGroupId)
        {
            this.sessionID = sessionID;
            this.scanId = scanId;
            this.skip = skip;
            this.take = take;
            this.calculateTotalResultsCount = calculateTotalResultsCount;
            this.queryGroupId = queryGroupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultsForQueryQroupWithPagingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultsForQueryQroupWithPagingResponse", Namespace="http://Checkmarx.com", Order=0)]
        public cxPriorityWebService.GetResultsForQueryQroupWithPagingResponseBody Body;
        
        public GetResultsForQueryQroupWithPagingResponse()
        {
        }
        
        public GetResultsForQueryQroupWithPagingResponse(cxPriorityWebService.GetResultsForQueryQroupWithPagingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Checkmarx.com")]
    public partial class GetResultsForQueryQroupWithPagingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryQroupWithPagingResult;
        
        public GetResultsForQueryQroupWithPagingResponseBody()
        {
        }
        
        public GetResultsForQueryQroupWithPagingResponseBody(cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryQroupWithPagingResult)
        {
            this.GetResultsForQueryQroupWithPagingResult = GetResultsForQueryQroupWithPagingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CxPriorityServiceSoapChannel : cxPriorityWebService.CxPriorityServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CxPriorityServiceSoapClient : System.ServiceModel.ClientBase<cxPriorityWebService.CxPriorityServiceSoap>, cxPriorityWebService.CxPriorityServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public CxPriorityServiceSoapClient(System.Uri endpointUrl, TimeSpan timeout, string username, string password)
             : base(CxPriorityServiceSoapClient.GetBindingForEndpoint(endpointUrl, timeout),
                   CxPriorityServiceSoapClient.GetEndpointAddress(endpointUrl.AbsoluteUri))
        {
            this.ChannelFactory.Credentials.UserName.UserName = username;
            this.ChannelFactory.Credentials.UserName.Password = password;
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cxPriorityWebService.GetResultsForQueryResponse cxPriorityWebService.CxPriorityServiceSoap.GetResultsForQuery(cxPriorityWebService.GetResultsForQueryRequest request)
        {
            return base.Channel.GetResultsForQuery(request);
        }
        
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQuery(string sessionID, long scanId, long queryId)
        {
            cxPriorityWebService.GetResultsForQueryRequest inValue = new cxPriorityWebService.GetResultsForQueryRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForQueryRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.queryId = queryId;
            cxPriorityWebService.GetResultsForQueryResponse retVal = ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForQuery(inValue);
            return retVal.Body.GetResultsForQueryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryResponse> cxPriorityWebService.CxPriorityServiceSoap.GetResultsForQueryAsync(cxPriorityWebService.GetResultsForQueryRequest request)
        {
            return base.Channel.GetResultsForQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryResponse> GetResultsForQueryAsync(string sessionID, long scanId, long queryId)
        {
            cxPriorityWebService.GetResultsForQueryRequest inValue = new cxPriorityWebService.GetResultsForQueryRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForQueryRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.queryId = queryId;
            return ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForQueryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cxPriorityWebService.GetResultsForQueryQroupResponse cxPriorityWebService.CxPriorityServiceSoap.GetResultsForQueryQroup(cxPriorityWebService.GetResultsForQueryQroupRequest request)
        {
            return base.Channel.GetResultsForQueryQroup(request);
        }
        
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryQroup(string sessionID, long scanId, long queryGroupId)
        {
            cxPriorityWebService.GetResultsForQueryQroupRequest inValue = new cxPriorityWebService.GetResultsForQueryQroupRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForQueryQroupRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.queryGroupId = queryGroupId;
            cxPriorityWebService.GetResultsForQueryQroupResponse retVal = ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForQueryQroup(inValue);
            return retVal.Body.GetResultsForQueryQroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryQroupResponse> cxPriorityWebService.CxPriorityServiceSoap.GetResultsForQueryQroupAsync(cxPriorityWebService.GetResultsForQueryQroupRequest request)
        {
            return base.Channel.GetResultsForQueryQroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryQroupResponse> GetResultsForQueryQroupAsync(string sessionID, long scanId, long queryGroupId)
        {
            cxPriorityWebService.GetResultsForQueryQroupRequest inValue = new cxPriorityWebService.GetResultsForQueryQroupRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForQueryQroupRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.queryGroupId = queryGroupId;
            return ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForQueryQroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cxPriorityWebService.GetResultsForScanByLanguageResponse cxPriorityWebService.CxPriorityServiceSoap.GetResultsForScanByLanguage(cxPriorityWebService.GetResultsForScanByLanguageRequest request)
        {
            return base.Channel.GetResultsForScanByLanguage(request);
        }
        
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanByLanguage(string sessionID, long scanId, string Language)
        {
            cxPriorityWebService.GetResultsForScanByLanguageRequest inValue = new cxPriorityWebService.GetResultsForScanByLanguageRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForScanByLanguageRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.Language = Language;
            cxPriorityWebService.GetResultsForScanByLanguageResponse retVal = ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForScanByLanguage(inValue);
            return retVal.Body.GetResultsForScanByLanguageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanByLanguageResponse> cxPriorityWebService.CxPriorityServiceSoap.GetResultsForScanByLanguageAsync(cxPriorityWebService.GetResultsForScanByLanguageRequest request)
        {
            return base.Channel.GetResultsForScanByLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanByLanguageResponse> GetResultsForScanByLanguageAsync(string sessionID, long scanId, string Language)
        {
            cxPriorityWebService.GetResultsForScanByLanguageRequest inValue = new cxPriorityWebService.GetResultsForScanByLanguageRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForScanByLanguageRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.Language = Language;
            return ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForScanByLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cxPriorityWebService.GetResultsForScanResponse cxPriorityWebService.CxPriorityServiceSoap.GetResultsForScan(cxPriorityWebService.GetResultsForScanRequest request)
        {
            return base.Channel.GetResultsForScan(request);
        }

        internal cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScan(string sessionID, long scanId)
        {
            cxPriorityWebService.GetResultsForScanRequest inValue = new cxPriorityWebService.GetResultsForScanRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForScanRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            cxPriorityWebService.GetResultsForScanResponse retVal = ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForScan(inValue);
            return retVal.Body.GetResultsForScanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanResponse> cxPriorityWebService.CxPriorityServiceSoap.GetResultsForScanAsync(cxPriorityWebService.GetResultsForScanRequest request)
        {
            return base.Channel.GetResultsForScanAsync(request);
        }
        
        public System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanResponse> GetResultsForScanAsync(string sessionID, long scanId)
        {
            cxPriorityWebService.GetResultsForScanRequest inValue = new cxPriorityWebService.GetResultsForScanRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForScanRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            return ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForScanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cxPriorityWebService.GetResultsBySeverityResponse cxPriorityWebService.CxPriorityServiceSoap.GetResultsBySeverity(cxPriorityWebService.GetResultsBySeverityRequest request)
        {
            return base.Channel.GetResultsBySeverity(request);
        }
        
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsBySeverity(string sessionId, long scanId, int Severity, string Language)
        {
            cxPriorityWebService.GetResultsBySeverityRequest inValue = new cxPriorityWebService.GetResultsBySeverityRequest();
            inValue.Body = new cxPriorityWebService.GetResultsBySeverityRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.scanId = scanId;
            inValue.Body.Severity = Severity;
            inValue.Body.Language = Language;
            cxPriorityWebService.GetResultsBySeverityResponse retVal = ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsBySeverity(inValue);
            return retVal.Body.GetResultsBySeverityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsBySeverityResponse> cxPriorityWebService.CxPriorityServiceSoap.GetResultsBySeverityAsync(cxPriorityWebService.GetResultsBySeverityRequest request)
        {
            return base.Channel.GetResultsBySeverityAsync(request);
        }
        
        public System.Threading.Tasks.Task<cxPriorityWebService.GetResultsBySeverityResponse> GetResultsBySeverityAsync(string sessionId, long scanId, int Severity, string Language)
        {
            cxPriorityWebService.GetResultsBySeverityRequest inValue = new cxPriorityWebService.GetResultsBySeverityRequest();
            inValue.Body = new cxPriorityWebService.GetResultsBySeverityRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.scanId = scanId;
            inValue.Body.Severity = Severity;
            inValue.Body.Language = Language;
            return ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsBySeverityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cxPriorityWebService.GetResultsForQueryWithPagingResponse cxPriorityWebService.CxPriorityServiceSoap.GetResultsForQueryWithPaging(cxPriorityWebService.GetResultsForQueryWithPagingRequest request)
        {
            return base.Channel.GetResultsForQueryWithPaging(request);
        }
        
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryWithPaging(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount, long queryId)
        {
            cxPriorityWebService.GetResultsForQueryWithPagingRequest inValue = new cxPriorityWebService.GetResultsForQueryWithPagingRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForQueryWithPagingRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            inValue.Body.calculateTotalResultsCount = calculateTotalResultsCount;
            inValue.Body.queryId = queryId;
            cxPriorityWebService.GetResultsForQueryWithPagingResponse retVal = ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForQueryWithPaging(inValue);
            return retVal.Body.GetResultsForQueryWithPagingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryWithPagingResponse> cxPriorityWebService.CxPriorityServiceSoap.GetResultsForQueryWithPagingAsync(cxPriorityWebService.GetResultsForQueryWithPagingRequest request)
        {
            return base.Channel.GetResultsForQueryWithPagingAsync(request);
        }
        
        public System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryWithPagingResponse> GetResultsForQueryWithPagingAsync(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount, long queryId)
        {
            cxPriorityWebService.GetResultsForQueryWithPagingRequest inValue = new cxPriorityWebService.GetResultsForQueryWithPagingRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForQueryWithPagingRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            inValue.Body.calculateTotalResultsCount = calculateTotalResultsCount;
            inValue.Body.queryId = queryId;
            return ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForQueryWithPagingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cxPriorityWebService.GetResultsForScanByLanguageWithPagingResponse cxPriorityWebService.CxPriorityServiceSoap.GetResultsForScanByLanguageWithPaging(cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequest request)
        {
            return base.Channel.GetResultsForScanByLanguageWithPaging(request);
        }
        
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanByLanguageWithPaging(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount, string Language)
        {
            cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequest inValue = new cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            inValue.Body.calculateTotalResultsCount = calculateTotalResultsCount;
            inValue.Body.Language = Language;
            cxPriorityWebService.GetResultsForScanByLanguageWithPagingResponse retVal = ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForScanByLanguageWithPaging(inValue);
            return retVal.Body.GetResultsForScanByLanguageWithPagingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanByLanguageWithPagingResponse> cxPriorityWebService.CxPriorityServiceSoap.GetResultsForScanByLanguageWithPagingAsync(cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequest request)
        {
            return base.Channel.GetResultsForScanByLanguageWithPagingAsync(request);
        }
        
        public System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanByLanguageWithPagingResponse> GetResultsForScanByLanguageWithPagingAsync(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount, string Language)
        {
            cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequest inValue = new cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForScanByLanguageWithPagingRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            inValue.Body.calculateTotalResultsCount = calculateTotalResultsCount;
            inValue.Body.Language = Language;
            return ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForScanByLanguageWithPagingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cxPriorityWebService.GetResultsForScanWithPagingResponse cxPriorityWebService.CxPriorityServiceSoap.GetResultsForScanWithPaging(cxPriorityWebService.GetResultsForScanWithPagingRequest request)
        {
            return base.Channel.GetResultsForScanWithPaging(request);
        }
        
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForScanWithPaging(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount)
        {
            cxPriorityWebService.GetResultsForScanWithPagingRequest inValue = new cxPriorityWebService.GetResultsForScanWithPagingRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForScanWithPagingRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            inValue.Body.calculateTotalResultsCount = calculateTotalResultsCount;
            cxPriorityWebService.GetResultsForScanWithPagingResponse retVal = ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForScanWithPaging(inValue);
            return retVal.Body.GetResultsForScanWithPagingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanWithPagingResponse> cxPriorityWebService.CxPriorityServiceSoap.GetResultsForScanWithPagingAsync(cxPriorityWebService.GetResultsForScanWithPagingRequest request)
        {
            return base.Channel.GetResultsForScanWithPagingAsync(request);
        }
        
        public System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForScanWithPagingResponse> GetResultsForScanWithPagingAsync(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount)
        {
            cxPriorityWebService.GetResultsForScanWithPagingRequest inValue = new cxPriorityWebService.GetResultsForScanWithPagingRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForScanWithPagingRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            inValue.Body.calculateTotalResultsCount = calculateTotalResultsCount;
            return ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForScanWithPagingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cxPriorityWebService.GetResultsBySeverityWithPagingResponse cxPriorityWebService.CxPriorityServiceSoap.GetResultsBySeverityWithPaging(cxPriorityWebService.GetResultsBySeverityWithPagingRequest request)
        {
            return base.Channel.GetResultsBySeverityWithPaging(request);
        }
        
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsBySeverityWithPaging(string sessionId, long scanId, int skip, int take, bool calculateTotalResultsCount, int Severity, string Language)
        {
            cxPriorityWebService.GetResultsBySeverityWithPagingRequest inValue = new cxPriorityWebService.GetResultsBySeverityWithPagingRequest();
            inValue.Body = new cxPriorityWebService.GetResultsBySeverityWithPagingRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.scanId = scanId;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            inValue.Body.calculateTotalResultsCount = calculateTotalResultsCount;
            inValue.Body.Severity = Severity;
            inValue.Body.Language = Language;
            cxPriorityWebService.GetResultsBySeverityWithPagingResponse retVal = ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsBySeverityWithPaging(inValue);
            return retVal.Body.GetResultsBySeverityWithPagingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsBySeverityWithPagingResponse> cxPriorityWebService.CxPriorityServiceSoap.GetResultsBySeverityWithPagingAsync(cxPriorityWebService.GetResultsBySeverityWithPagingRequest request)
        {
            return base.Channel.GetResultsBySeverityWithPagingAsync(request);
        }
        
        public System.Threading.Tasks.Task<cxPriorityWebService.GetResultsBySeverityWithPagingResponse> GetResultsBySeverityWithPagingAsync(string sessionId, long scanId, int skip, int take, bool calculateTotalResultsCount, int Severity, string Language)
        {
            cxPriorityWebService.GetResultsBySeverityWithPagingRequest inValue = new cxPriorityWebService.GetResultsBySeverityWithPagingRequest();
            inValue.Body = new cxPriorityWebService.GetResultsBySeverityWithPagingRequestBody();
            inValue.Body.sessionId = sessionId;
            inValue.Body.scanId = scanId;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            inValue.Body.calculateTotalResultsCount = calculateTotalResultsCount;
            inValue.Body.Severity = Severity;
            inValue.Body.Language = Language;
            return ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsBySeverityWithPagingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cxPriorityWebService.GetResultsForQueryQroupWithPagingResponse cxPriorityWebService.CxPriorityServiceSoap.GetResultsForQueryQroupWithPaging(cxPriorityWebService.GetResultsForQueryQroupWithPagingRequest request)
        {
            return base.Channel.GetResultsForQueryQroupWithPaging(request);
        }
        
        public cxPriorityWebService.CxWSResponseScanResultsPriority GetResultsForQueryQroupWithPaging(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount, long queryGroupId)
        {
            cxPriorityWebService.GetResultsForQueryQroupWithPagingRequest inValue = new cxPriorityWebService.GetResultsForQueryQroupWithPagingRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForQueryQroupWithPagingRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            inValue.Body.calculateTotalResultsCount = calculateTotalResultsCount;
            inValue.Body.queryGroupId = queryGroupId;
            cxPriorityWebService.GetResultsForQueryQroupWithPagingResponse retVal = ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForQueryQroupWithPaging(inValue);
            return retVal.Body.GetResultsForQueryQroupWithPagingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryQroupWithPagingResponse> cxPriorityWebService.CxPriorityServiceSoap.GetResultsForQueryQroupWithPagingAsync(cxPriorityWebService.GetResultsForQueryQroupWithPagingRequest request)
        {
            return base.Channel.GetResultsForQueryQroupWithPagingAsync(request);
        }
        
        public System.Threading.Tasks.Task<cxPriorityWebService.GetResultsForQueryQroupWithPagingResponse> GetResultsForQueryQroupWithPagingAsync(string sessionID, long scanId, int skip, int take, bool calculateTotalResultsCount, long queryGroupId)
        {
            cxPriorityWebService.GetResultsForQueryQroupWithPagingRequest inValue = new cxPriorityWebService.GetResultsForQueryQroupWithPagingRequest();
            inValue.Body = new cxPriorityWebService.GetResultsForQueryQroupWithPagingRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.scanId = scanId;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            inValue.Body.calculateTotalResultsCount = calculateTotalResultsCount;
            inValue.Body.queryGroupId = queryGroupId;
            return ((cxPriorityWebService.CxPriorityServiceSoap)(this)).GetResultsForQueryQroupWithPagingAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(Uri url, TimeSpan timeout)
        {
            HttpBindingBase httpBinding = null;
            if (url.Scheme == Uri.UriSchemeHttps)
            {
                httpBinding = new BasicHttpsBinding();
                ((BasicHttpsBinding)httpBinding).Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
                ((BasicHttpsBinding)httpBinding).Security.Mode = BasicHttpsSecurityMode.Transport;
            }
            else
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }

            var integerMaxValue = int.MaxValue;
            httpBinding.MaxBufferSize = integerMaxValue;
            httpBinding.MaxReceivedMessageSize = integerMaxValue;
            httpBinding.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            httpBinding.AllowCookies = true;

            httpBinding.ReceiveTimeout = timeout;
            httpBinding.SendTimeout = timeout;
            httpBinding.OpenTimeout = timeout;
            httpBinding.CloseTimeout = timeout;

            return httpBinding;
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(string endpointUrl)
        {
            endpointUrl += "CxWebInterface/Priority/CxPriorityService.asmx";

            return new System.ServiceModel.EndpointAddress(endpointUrl);
        }

        public enum EndpointConfiguration
        {
            
            CxPriorityServiceSoap,
            
            CxPriorityServiceSoap12,
        }
    }
}
