//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/5/2022 1:06:25 PM
namespace Checkmarx.API.SAST.OData
{
    /// <summary>
    /// There are no comments for ProjectSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ProjectSingle")]
    public partial class ProjectSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Project>
    {
        /// <summary>
        /// Initialize a new ProjectSingle object.
        /// </summary>
        public ProjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProjectSingle object.
        /// </summary>
        public ProjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProjectSingle object.
        /// </summary>
        public ProjectSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Project> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Scans in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Scans")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Checkmarx.API.SAST.OData.Scan> Scans
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Scans == null))
                {
                    this._Scans = Context.CreateQuery<Checkmarx.API.SAST.OData.Scan>(GetPath("Scans"));
                }
                return this._Scans;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<Checkmarx.API.SAST.OData.Scan> _Scans;
        /// <summary>
        /// There are no comments for CustomFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CustomFields")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Checkmarx.API.SAST.OData.ProjectCustomField> CustomFields
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CustomFields == null))
                {
                    this._CustomFields = Context.CreateQuery<Checkmarx.API.SAST.OData.ProjectCustomField>(GetPath("CustomFields"));
                }
                return this._CustomFields;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<Checkmarx.API.SAST.OData.ProjectCustomField> _CustomFields;
        /// <summary>
        /// There are no comments for EngineConfiguration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EngineConfiguration")]
        public virtual Checkmarx.API.SAST.OData.EngineConfigurationSingle EngineConfiguration
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._EngineConfiguration == null))
                {
                    this._EngineConfiguration = new Checkmarx.API.SAST.OData.EngineConfigurationSingle(this.Context, GetPath("EngineConfiguration"));
                }
                return this._EngineConfiguration;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.EngineConfigurationSingle _EngineConfiguration;
        /// <summary>
        /// There are no comments for ClientType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ClientType")]
        public virtual Checkmarx.API.SAST.OData.ClientTypeSingle ClientType
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ClientType == null))
                {
                    this._ClientType = new Checkmarx.API.SAST.OData.ClientTypeSingle(this.Context, GetPath("ClientType"));
                }
                return this._ClientType;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.ClientTypeSingle _ClientType;
        /// <summary>
        /// There are no comments for OwningUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OwningUser")]
        public virtual Checkmarx.API.SAST.OData.UserSingle OwningUser
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._OwningUser == null))
                {
                    this._OwningUser = new Checkmarx.API.SAST.OData.UserSingle(this.Context, GetPath("OwningUser"));
                }
                return this._OwningUser;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.UserSingle _OwningUser;
        /// <summary>
        /// There are no comments for OwningTeam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OwningTeam")]
        public virtual Checkmarx.API.SAST.OData.TeamSingle OwningTeam
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._OwningTeam == null))
                {
                    this._OwningTeam = new Checkmarx.API.SAST.OData.TeamSingle(this.Context, GetPath("OwningTeam"));
                }
                return this._OwningTeam;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.TeamSingle _OwningTeam;
        /// <summary>
        /// There are no comments for Preset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Preset")]
        public virtual Checkmarx.API.SAST.OData.PresetSingle Preset
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Preset == null))
                {
                    this._Preset = new Checkmarx.API.SAST.OData.PresetSingle(this.Context, GetPath("Preset"));
                }
                return this._Preset;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.PresetSingle _Preset;
        /// <summary>
        /// There are no comments for LastScan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastScan")]
        public virtual Checkmarx.API.SAST.OData.ScanSingle LastScan
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LastScan == null))
                {
                    this._LastScan = new Checkmarx.API.SAST.OData.ScanSingle(this.Context, GetPath("LastScan"));
                }
                return this._LastScan;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.ScanSingle _LastScan;
    }
    /// <summary>
    /// There are no comments for Project in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Project")]
    public partial class Project : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="isPublic">Initial value of IsPublic.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="owningTeamId">Initial value of OwningTeamId.</param>
        /// <param name="originClientTypeId">Initial value of OriginClientTypeId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Project CreateProject(long ID, bool isPublic, global::System.DateTimeOffset createdDate, int owningTeamId, int originClientTypeId)
        {
            Project project = new Project();
            project.Id = ID;
            project.IsPublic = isPublic;
            project.CreatedDate = createdDate;
            project.OwningTeamId = owningTeamId;
            project.OriginClientTypeId = originClientTypeId;
            return project;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property IsPublic in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsPublic")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "IsPublic is required.")]
        public virtual bool IsPublic
        {
            get
            {
                return this._IsPublic;
            }
            set
            {
                this.OnIsPublicChanging(value);
                this._IsPublic = value;
                this.OnIsPublicChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _IsPublic;
        partial void OnIsPublicChanging(bool value);
        partial void OnIsPublicChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedDate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CreatedDate is required.")]
        public virtual global::System.DateTimeOffset CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTimeOffset value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property OwnerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OwnerId")]
        public virtual global::System.Nullable<int> OwnerId
        {
            get
            {
                return this._OwnerId;
            }
            set
            {
                this.OnOwnerIdChanging(value);
                this._OwnerId = value;
                this.OnOwnerIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _OwnerId;
        partial void OnOwnerIdChanging(global::System.Nullable<int> value);
        partial void OnOwnerIdChanged();
        /// <summary>
        /// There are no comments for Property OwningTeamId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OwningTeamId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "OwningTeamId is required.")]
        public virtual int OwningTeamId
        {
            get
            {
                return this._OwningTeamId;
            }
            set
            {
                this.OnOwningTeamIdChanging(value);
                this._OwningTeamId = value;
                this.OnOwningTeamIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _OwningTeamId;
        partial void OnOwningTeamIdChanging(int value);
        partial void OnOwningTeamIdChanged();
        /// <summary>
        /// There are no comments for Property EngineConfigurationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EngineConfigurationId")]
        public virtual global::System.Nullable<long> EngineConfigurationId
        {
            get
            {
                return this._EngineConfigurationId;
            }
            set
            {
                this.OnEngineConfigurationIdChanging(value);
                this._EngineConfigurationId = value;
                this.OnEngineConfigurationIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _EngineConfigurationId;
        partial void OnEngineConfigurationIdChanging(global::System.Nullable<long> value);
        partial void OnEngineConfigurationIdChanged();
        /// <summary>
        /// There are no comments for Property IssueTrackingSettings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IssueTrackingSettings")]
        public virtual string IssueTrackingSettings
        {
            get
            {
                return this._IssueTrackingSettings;
            }
            set
            {
                this.OnIssueTrackingSettingsChanging(value);
                this._IssueTrackingSettings = value;
                this.OnIssueTrackingSettingsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _IssueTrackingSettings;
        partial void OnIssueTrackingSettingsChanging(string value);
        partial void OnIssueTrackingSettingsChanged();
        /// <summary>
        /// There are no comments for Property SourcePath in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SourcePath")]
        public virtual string SourcePath
        {
            get
            {
                return this._SourcePath;
            }
            set
            {
                this.OnSourcePathChanging(value);
                this._SourcePath = value;
                this.OnSourcePathChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SourcePath;
        partial void OnSourcePathChanging(string value);
        partial void OnSourcePathChanged();
        /// <summary>
        /// There are no comments for Property SourceProviderCredentials in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SourceProviderCredentials")]
        public virtual string SourceProviderCredentials
        {
            get
            {
                return this._SourceProviderCredentials;
            }
            set
            {
                this.OnSourceProviderCredentialsChanging(value);
                this._SourceProviderCredentials = value;
                this.OnSourceProviderCredentialsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SourceProviderCredentials;
        partial void OnSourceProviderCredentialsChanging(string value);
        partial void OnSourceProviderCredentialsChanged();
        /// <summary>
        /// There are no comments for Property ExcludedFiles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ExcludedFiles")]
        public virtual string ExcludedFiles
        {
            get
            {
                return this._ExcludedFiles;
            }
            set
            {
                this.OnExcludedFilesChanging(value);
                this._ExcludedFiles = value;
                this.OnExcludedFilesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ExcludedFiles;
        partial void OnExcludedFilesChanging(string value);
        partial void OnExcludedFilesChanged();
        /// <summary>
        /// There are no comments for Property ExcludedFolders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ExcludedFolders")]
        public virtual string ExcludedFolders
        {
            get
            {
                return this._ExcludedFolders;
            }
            set
            {
                this.OnExcludedFoldersChanging(value);
                this._ExcludedFolders = value;
                this.OnExcludedFoldersChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ExcludedFolders;
        partial void OnExcludedFoldersChanging(string value);
        partial void OnExcludedFoldersChanged();
        /// <summary>
        /// There are no comments for Property OriginClientTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OriginClientTypeId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "OriginClientTypeId is required.")]
        public virtual int OriginClientTypeId
        {
            get
            {
                return this._OriginClientTypeId;
            }
            set
            {
                this.OnOriginClientTypeIdChanging(value);
                this._OriginClientTypeId = value;
                this.OnOriginClientTypeIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _OriginClientTypeId;
        partial void OnOriginClientTypeIdChanging(int value);
        partial void OnOriginClientTypeIdChanged();
        /// <summary>
        /// There are no comments for Property PresetId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PresetId")]
        public virtual global::System.Nullable<long> PresetId
        {
            get
            {
                return this._PresetId;
            }
            set
            {
                this.OnPresetIdChanging(value);
                this._PresetId = value;
                this.OnPresetIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _PresetId;
        partial void OnPresetIdChanging(global::System.Nullable<long> value);
        partial void OnPresetIdChanged();
        /// <summary>
        /// There are no comments for Property LastScanId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LastScanId")]
        public virtual global::System.Nullable<long> LastScanId
        {
            get
            {
                return this._LastScanId;
            }
            set
            {
                this.OnLastScanIdChanging(value);
                this._LastScanId = value;
                this.OnLastScanIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _LastScanId;
        partial void OnLastScanIdChanging(global::System.Nullable<long> value);
        partial void OnLastScanIdChanged();
        /// <summary>
        /// There are no comments for Property TotalProjectScanCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TotalProjectScanCount")]
        public virtual global::System.Nullable<int> TotalProjectScanCount
        {
            get
            {
                return this._TotalProjectScanCount;
            }
            set
            {
                this.OnTotalProjectScanCountChanging(value);
                this._TotalProjectScanCount = value;
                this.OnTotalProjectScanCountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _TotalProjectScanCount;
        partial void OnTotalProjectScanCountChanging(global::System.Nullable<int> value);
        partial void OnTotalProjectScanCountChanged();
        /// <summary>
        /// There are no comments for Property SchedulingExpression in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SchedulingExpression")]
        public virtual string SchedulingExpression
        {
            get
            {
                return this._SchedulingExpression;
            }
            set
            {
                this.OnSchedulingExpressionChanging(value);
                this._SchedulingExpression = value;
                this.OnSchedulingExpressionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SchedulingExpression;
        partial void OnSchedulingExpressionChanging(string value);
        partial void OnSchedulingExpressionChanged();
        /// <summary>
        /// There are no comments for Property Scans in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Scans")]
        public virtual global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.Scan> Scans
        {
            get
            {
                return this._Scans;
            }
            set
            {
                this.OnScansChanging(value);
                this._Scans = value;
                this.OnScansChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.Scan> _Scans = new global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.Scan>();
        partial void OnScansChanging(global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.Scan> value);
        partial void OnScansChanged();
        /// <summary>
        /// There are no comments for Property CustomFields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CustomFields")]
        public virtual global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.ProjectCustomField> CustomFields
        {
            get
            {
                return this._CustomFields;
            }
            set
            {
                this.OnCustomFieldsChanging(value);
                this._CustomFields = value;
                this.OnCustomFieldsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.ProjectCustomField> _CustomFields = new global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.ProjectCustomField>();
        partial void OnCustomFieldsChanging(global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.ProjectCustomField> value);
        partial void OnCustomFieldsChanged();
        /// <summary>
        /// There are no comments for Property EngineConfiguration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EngineConfiguration")]
        public virtual Checkmarx.API.SAST.OData.EngineConfiguration EngineConfiguration
        {
            get
            {
                return this._EngineConfiguration;
            }
            set
            {
                this.OnEngineConfigurationChanging(value);
                this._EngineConfiguration = value;
                this.OnEngineConfigurationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.EngineConfiguration _EngineConfiguration;
        partial void OnEngineConfigurationChanging(Checkmarx.API.SAST.OData.EngineConfiguration value);
        partial void OnEngineConfigurationChanged();
        /// <summary>
        /// There are no comments for Property ClientType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ClientType")]
        public virtual Checkmarx.API.SAST.OData.ClientType ClientType
        {
            get
            {
                return this._ClientType;
            }
            set
            {
                this.OnClientTypeChanging(value);
                this._ClientType = value;
                this.OnClientTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.ClientType _ClientType;
        partial void OnClientTypeChanging(Checkmarx.API.SAST.OData.ClientType value);
        partial void OnClientTypeChanged();
        /// <summary>
        /// There are no comments for Property OwningUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OwningUser")]
        public virtual Checkmarx.API.SAST.OData.User OwningUser
        {
            get
            {
                return this._OwningUser;
            }
            set
            {
                this.OnOwningUserChanging(value);
                this._OwningUser = value;
                this.OnOwningUserChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.User _OwningUser;
        partial void OnOwningUserChanging(Checkmarx.API.SAST.OData.User value);
        partial void OnOwningUserChanged();
        /// <summary>
        /// There are no comments for Property OwningTeam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OwningTeam")]
        public virtual Checkmarx.API.SAST.OData.Team OwningTeam
        {
            get
            {
                return this._OwningTeam;
            }
            set
            {
                this.OnOwningTeamChanging(value);
                this._OwningTeam = value;
                this.OnOwningTeamChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.Team _OwningTeam;
        partial void OnOwningTeamChanging(Checkmarx.API.SAST.OData.Team value);
        partial void OnOwningTeamChanged();
        /// <summary>
        /// There are no comments for Property Preset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Preset")]
        public virtual Checkmarx.API.SAST.OData.Preset Preset
        {
            get
            {
                return this._Preset;
            }
            set
            {
                this.OnPresetChanging(value);
                this._Preset = value;
                this.OnPresetChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.Preset _Preset;
        partial void OnPresetChanging(Checkmarx.API.SAST.OData.Preset value);
        partial void OnPresetChanged();
        /// <summary>
        /// There are no comments for Property LastScan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LastScan")]
        public virtual Checkmarx.API.SAST.OData.Scan LastScan
        {
            get
            {
                return this._LastScan;
            }
            set
            {
                this.OnLastScanChanging(value);
                this._LastScan = value;
                this.OnLastScanChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.Scan _LastScan;
        partial void OnLastScanChanging(Checkmarx.API.SAST.OData.Scan value);
        partial void OnLastScanChanged();
    }
}
