//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/5/2022 1:06:25 PM
namespace Checkmarx.API.SAST.OData
{
    /// <summary>
    /// There are no comments for QueryGroupTypeSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("QueryGroupTypeSingle")]
    public partial class QueryGroupTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<QueryGroupType>
    {
        /// <summary>
        /// Initialize a new QueryGroupTypeSingle object.
        /// </summary>
        public QueryGroupTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new QueryGroupTypeSingle object.
        /// </summary>
        public QueryGroupTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new QueryGroupTypeSingle object.
        /// </summary>
        public QueryGroupTypeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<QueryGroupType> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for QueryGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryGroups")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Checkmarx.API.SAST.OData.QueryGroup> QueryGroups
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._QueryGroups == null))
                {
                    this._QueryGroups = Context.CreateQuery<Checkmarx.API.SAST.OData.QueryGroup>(GetPath("QueryGroups"));
                }
                return this._QueryGroups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<Checkmarx.API.SAST.OData.QueryGroup> _QueryGroups;
    }
    /// <summary>
    /// There are no comments for QueryGroupType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("QueryGroupType")]
    public partial class QueryGroupType : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new QueryGroupType object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static QueryGroupType CreateQueryGroupType(int ID)
        {
            QueryGroupType queryGroupType = new QueryGroupType();
            queryGroupType.Id = ID;
            return queryGroupType;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property QueryGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryGroups")]
        public virtual global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.QueryGroup> QueryGroups
        {
            get
            {
                return this._QueryGroups;
            }
            set
            {
                this.OnQueryGroupsChanging(value);
                this._QueryGroups = value;
                this.OnQueryGroupsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.QueryGroup> _QueryGroups = new global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.QueryGroup>();
        partial void OnQueryGroupsChanging(global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.QueryGroup> value);
        partial void OnQueryGroupsChanged();
    }
}
