//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/5/2022 1:06:25 PM
namespace Checkmarx.API.SAST.OData
{
    /// <summary>
    /// There are no comments for QuerySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("QuerySingle")]
    public partial class QuerySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Query>
    {
        /// <summary>
        /// Initialize a new QuerySingle object.
        /// </summary>
        public QuerySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new QuerySingle object.
        /// </summary>
        public QuerySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new QuerySingle object.
        /// </summary>
        public QuerySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Query> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for QueryCxDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryCxDescription")]
        public virtual Checkmarx.API.SAST.OData.QueryCxDescriptionSingle QueryCxDescription
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._QueryCxDescription == null))
                {
                    this._QueryCxDescription = new Checkmarx.API.SAST.OData.QueryCxDescriptionSingle(this.Context, GetPath("QueryCxDescription"));
                }
                return this._QueryCxDescription;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.QueryCxDescriptionSingle _QueryCxDescription;
        /// <summary>
        /// There are no comments for QueryCweDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryCweDescription")]
        public virtual Checkmarx.API.SAST.OData.QueryCweDescriptionSingle QueryCweDescription
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._QueryCweDescription == null))
                {
                    this._QueryCweDescription = new Checkmarx.API.SAST.OData.QueryCweDescriptionSingle(this.Context, GetPath("QueryCweDescription"));
                }
                return this._QueryCweDescription;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.QueryCweDescriptionSingle _QueryCweDescription;
        /// <summary>
        /// There are no comments for QuerySource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("QuerySource")]
        public virtual Checkmarx.API.SAST.OData.QuerySourceSingle QuerySource
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._QuerySource == null))
                {
                    this._QuerySource = new Checkmarx.API.SAST.OData.QuerySourceSingle(this.Context, GetPath("QuerySource"));
                }
                return this._QuerySource;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.QuerySourceSingle _QuerySource;
        /// <summary>
        /// There are no comments for QueryGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryGroup")]
        public virtual Checkmarx.API.SAST.OData.QueryGroupSingle QueryGroup
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._QueryGroup == null))
                {
                    this._QueryGroup = new Checkmarx.API.SAST.OData.QueryGroupSingle(this.Context, GetPath("QueryGroup"));
                }
                return this._QueryGroup;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.QueryGroupSingle _QueryGroup;
        /// <summary>
        /// There are no comments for QueryCategories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryCategories")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Checkmarx.API.SAST.OData.QueryCategory> QueryCategories
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._QueryCategories == null))
                {
                    this._QueryCategories = Context.CreateQuery<Checkmarx.API.SAST.OData.QueryCategory>(GetPath("QueryCategories"));
                }
                return this._QueryCategories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<Checkmarx.API.SAST.OData.QueryCategory> _QueryCategories;
    }
    /// <summary>
    /// There are no comments for Query in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Query")]
    public partial class Query : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Query object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="severity">Initial value of Severity.</param>
        /// <param name="cweId">Initial value of CweId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Query CreateQuery(long ID, long version, int severity, long cweId)
        {
            Query query = new Query();
            query.Id = ID;
            query.Version = version;
            query.Severity = severity;
            query.CweId = cweId;
            return query;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Version")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Version is required.")]
        public virtual long Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Version;
        partial void OnVersionChanging(long value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Severity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Severity")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Severity is required.")]
        public virtual int Severity
        {
            get
            {
                return this._Severity;
            }
            set
            {
                this.OnSeverityChanging(value);
                this._Severity = value;
                this.OnSeverityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Severity;
        partial void OnSeverityChanging(int value);
        partial void OnSeverityChanged();
        /// <summary>
        /// There are no comments for Property Comments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Comments")]
        public virtual string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this.OnCommentsChanging(value);
                this._Comments = value;
                this.OnCommentsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Comments;
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        /// <summary>
        /// There are no comments for Property CxDescriptionId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CxDescriptionId")]
        public virtual global::System.Nullable<int> CxDescriptionId
        {
            get
            {
                return this._CxDescriptionId;
            }
            set
            {
                this.OnCxDescriptionIdChanging(value);
                this._CxDescriptionId = value;
                this.OnCxDescriptionIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _CxDescriptionId;
        partial void OnCxDescriptionIdChanging(global::System.Nullable<int> value);
        partial void OnCxDescriptionIdChanged();
        /// <summary>
        /// There are no comments for Property CweId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CweId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CweId is required.")]
        public virtual long CweId
        {
            get
            {
                return this._CweId;
            }
            set
            {
                this.OnCweIdChanging(value);
                this._CweId = value;
                this.OnCweIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _CweId;
        partial void OnCweIdChanging(long value);
        partial void OnCweIdChanged();
        /// <summary>
        /// There are no comments for Property QuerySourceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("QuerySourceId")]
        public virtual global::System.Nullable<long> QuerySourceId
        {
            get
            {
                return this._QuerySourceId;
            }
            set
            {
                this.OnQuerySourceIdChanging(value);
                this._QuerySourceId = value;
                this.OnQuerySourceIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _QuerySourceId;
        partial void OnQuerySourceIdChanging(global::System.Nullable<long> value);
        partial void OnQuerySourceIdChanged();
        /// <summary>
        /// There are no comments for Property QueryGroupId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryGroupId")]
        public virtual global::System.Nullable<long> QueryGroupId
        {
            get
            {
                return this._QueryGroupId;
            }
            set
            {
                this.OnQueryGroupIdChanging(value);
                this._QueryGroupId = value;
                this.OnQueryGroupIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _QueryGroupId;
        partial void OnQueryGroupIdChanging(global::System.Nullable<long> value);
        partial void OnQueryGroupIdChanged();
        /// <summary>
        /// There are no comments for Property QueryCxDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryCxDescription")]
        public virtual Checkmarx.API.SAST.OData.QueryCxDescription QueryCxDescription
        {
            get
            {
                return this._QueryCxDescription;
            }
            set
            {
                this.OnQueryCxDescriptionChanging(value);
                this._QueryCxDescription = value;
                this.OnQueryCxDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.QueryCxDescription _QueryCxDescription;
        partial void OnQueryCxDescriptionChanging(Checkmarx.API.SAST.OData.QueryCxDescription value);
        partial void OnQueryCxDescriptionChanged();
        /// <summary>
        /// There are no comments for Property QueryCweDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryCweDescription")]
        public virtual Checkmarx.API.SAST.OData.QueryCweDescription QueryCweDescription
        {
            get
            {
                return this._QueryCweDescription;
            }
            set
            {
                this.OnQueryCweDescriptionChanging(value);
                this._QueryCweDescription = value;
                this.OnQueryCweDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.QueryCweDescription _QueryCweDescription;
        partial void OnQueryCweDescriptionChanging(Checkmarx.API.SAST.OData.QueryCweDescription value);
        partial void OnQueryCweDescriptionChanged();
        /// <summary>
        /// There are no comments for Property QuerySource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("QuerySource")]
        public virtual Checkmarx.API.SAST.OData.QuerySource QuerySource
        {
            get
            {
                return this._QuerySource;
            }
            set
            {
                this.OnQuerySourceChanging(value);
                this._QuerySource = value;
                this.OnQuerySourceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.QuerySource _QuerySource;
        partial void OnQuerySourceChanging(Checkmarx.API.SAST.OData.QuerySource value);
        partial void OnQuerySourceChanged();
        /// <summary>
        /// There are no comments for Property QueryGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryGroup")]
        public virtual Checkmarx.API.SAST.OData.QueryGroup QueryGroup
        {
            get
            {
                return this._QueryGroup;
            }
            set
            {
                this.OnQueryGroupChanging(value);
                this._QueryGroup = value;
                this.OnQueryGroupChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.QueryGroup _QueryGroup;
        partial void OnQueryGroupChanging(Checkmarx.API.SAST.OData.QueryGroup value);
        partial void OnQueryGroupChanged();
        /// <summary>
        /// There are no comments for Property QueryCategories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryCategories")]
        public virtual global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.QueryCategory> QueryCategories
        {
            get
            {
                return this._QueryCategories;
            }
            set
            {
                this.OnQueryCategoriesChanging(value);
                this._QueryCategories = value;
                this.OnQueryCategoriesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.QueryCategory> _QueryCategories = new global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.QueryCategory>();
        partial void OnQueryCategoriesChanging(global::System.Collections.ObjectModel.Collection<Checkmarx.API.SAST.OData.QueryCategory> value);
        partial void OnQueryCategoriesChanged();
    }
}
