//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/5/2022 1:06:25 PM
namespace Checkmarx.API.SAST.OData
{
    /// <summary>
    /// There are no comments for ScanResultSummaryDataSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ScanResultSummaryDataSingle")]
    public partial class ScanResultSummaryDataSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ScanResultSummaryData>
    {
        /// <summary>
        /// Initialize a new ScanResultSummaryDataSingle object.
        /// </summary>
        public ScanResultSummaryDataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ScanResultSummaryDataSingle object.
        /// </summary>
        public ScanResultSummaryDataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ScanResultSummaryDataSingle object.
        /// </summary>
        public ScanResultSummaryDataSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ScanResultSummaryData> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Scan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Scan")]
        public virtual Checkmarx.API.SAST.OData.ScanSingle Scan
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Scan == null))
                {
                    this._Scan = new Checkmarx.API.SAST.OData.ScanSingle(this.Context, GetPath("Scan"));
                }
                return this._Scan;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.ScanSingle _Scan;
        /// <summary>
        /// There are no comments for PreviousScan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PreviousScan")]
        public virtual Checkmarx.API.SAST.OData.ScanSingle PreviousScan
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PreviousScan == null))
                {
                    this._PreviousScan = new Checkmarx.API.SAST.OData.ScanSingle(this.Context, GetPath("PreviousScan"));
                }
                return this._PreviousScan;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.ScanSingle _PreviousScan;
    }
    /// <summary>
    /// There are no comments for ScanResultSummaryData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ScanId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ScanId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ScanResultSummaryData")]
    public partial class ScanResultSummaryData : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new ScanResultSummaryData object.
        /// </summary>
        /// <param name="new">Initial value of New.</param>
        /// <param name="recurrent">Initial value of Recurrent.</param>
        /// <param name="resolved">Initial value of Resolved.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static ScanResultSummaryData CreateScanResultSummaryData(int @new, int recurrent, int resolved)
        {
            ScanResultSummaryData scanResultSummaryData = new ScanResultSummaryData();
            scanResultSummaryData.New = @new;
            scanResultSummaryData.Recurrent = recurrent;
            scanResultSummaryData.Resolved = resolved;
            return scanResultSummaryData;
        }
        /// <summary>
        /// There are no comments for Property ScanId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ScanId")]
        public virtual global::System.Nullable<long> ScanId
        {
            get
            {
                return this._ScanId;
            }
            set
            {
                this.OnScanIdChanging(value);
                this._ScanId = value;
                this.OnScanIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _ScanId;
        partial void OnScanIdChanging(global::System.Nullable<long> value);
        partial void OnScanIdChanged();
        /// <summary>
        /// There are no comments for Property PreviousScanId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PreviousScanId")]
        public virtual global::System.Nullable<long> PreviousScanId
        {
            get
            {
                return this._PreviousScanId;
            }
            set
            {
                this.OnPreviousScanIdChanging(value);
                this._PreviousScanId = value;
                this.OnPreviousScanIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<long> _PreviousScanId;
        partial void OnPreviousScanIdChanging(global::System.Nullable<long> value);
        partial void OnPreviousScanIdChanged();
        /// <summary>
        /// There are no comments for Property New in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("New")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "New is required.")]
        public virtual int New
        {
            get
            {
                return this._New;
            }
            set
            {
                this.OnNewChanging(value);
                this._New = value;
                this.OnNewChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _New;
        partial void OnNewChanging(int value);
        partial void OnNewChanged();
        /// <summary>
        /// There are no comments for Property Recurrent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Recurrent")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Recurrent is required.")]
        public virtual int Recurrent
        {
            get
            {
                return this._Recurrent;
            }
            set
            {
                this.OnRecurrentChanging(value);
                this._Recurrent = value;
                this.OnRecurrentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Recurrent;
        partial void OnRecurrentChanging(int value);
        partial void OnRecurrentChanged();
        /// <summary>
        /// There are no comments for Property Resolved in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Resolved")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Resolved is required.")]
        public virtual int Resolved
        {
            get
            {
                return this._Resolved;
            }
            set
            {
                this.OnResolvedChanging(value);
                this._Resolved = value;
                this.OnResolvedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Resolved;
        partial void OnResolvedChanging(int value);
        partial void OnResolvedChanged();
        /// <summary>
        /// There are no comments for Property Scan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Scan")]
        public virtual Checkmarx.API.SAST.OData.Scan Scan
        {
            get
            {
                return this._Scan;
            }
            set
            {
                this.OnScanChanging(value);
                this._Scan = value;
                this.OnScanChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.Scan _Scan;
        partial void OnScanChanging(Checkmarx.API.SAST.OData.Scan value);
        partial void OnScanChanged();
        /// <summary>
        /// There are no comments for Property PreviousScan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PreviousScan")]
        public virtual Checkmarx.API.SAST.OData.Scan PreviousScan
        {
            get
            {
                return this._PreviousScan;
            }
            set
            {
                this.OnPreviousScanChanging(value);
                this._PreviousScan = value;
                this.OnPreviousScanChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private Checkmarx.API.SAST.OData.Scan _PreviousScan;
        partial void OnPreviousScanChanging(Checkmarx.API.SAST.OData.Scan value);
        partial void OnPreviousScanChanged();
    }
}
