//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 10/5/2022 1:06:25 PM
namespace Checkmarx.API.SAST.OData
{
    /// <summary>
    /// There are no comments for Severity in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Severity")]
    public enum Severity
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Info")]
        Info = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Low")]
        Low = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Medium")]
        Medium = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("High")]
        High = 3
    }
}
